package com.example.demo.model;

import java.io.Serializable;
import java.util.Date;

public class CpsMember implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.Md5_password
     *
     * @mbggenerated
     */
    private String md5Password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.weixin
     *
     * @mbggenerated
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.member_type_id
     *
     * @mbggenerated
     */
    private Integer memberTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.member_type_name
     *
     * @mbggenerated
     */
    private String memberTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.vip_level
     *
     * @mbggenerated
     */
    private Integer vipLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.buy_time
     *
     * @mbggenerated
     */
    private Date buyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.aging
     *
     * @mbggenerated
     */
    private Integer aging;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.points
     *
     * @mbggenerated
     */
    private Integer points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.last_login
     *
     * @mbggenerated
     */
    private Date lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.last_loginIp
     *
     * @mbggenerated
     */
    private String lastLoginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.register_ip
     *
     * @mbggenerated
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.UUID_token
     *
     * @mbggenerated
     */
    private String uuidToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.total_money
     *
     * @mbggenerated
     */
    private Integer totalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.is_lock
     *
     * @mbggenerated
     */
    private Integer isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.is_del
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.gmt_created
     *
     * @mbggenerated
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.pic_address
     *
     * @mbggenerated
     */
    private String picAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cps_member.favorites_ids
     *
     * @mbggenerated
     */
    private String favoritesIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cps_member
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cps_member
     *
     * @mbggenerated
     */
    public CpsMember(Integer id, String username, String nickname, String password, String md5Password, Integer gender, String mobile, String qq, String weixin, String email, Integer memberTypeId, String memberTypeName, Integer vipLevel, Date buyTime, Date endTime, Integer aging, Date birthday, Integer points, Date lastLogin, String lastLoginip, Date registerTime, String registerIp, String uuidToken, Integer totalMoney, Integer isLock, Integer isDel, Date gmtCreated, Date gmtModified, String picAddress, String favoritesIds) {
        this.id = id;
        this.username = username;
        this.nickname = nickname;
        this.password = password;
        this.md5Password = md5Password;
        this.gender = gender;
        this.mobile = mobile;
        this.qq = qq;
        this.weixin = weixin;
        this.email = email;
        this.memberTypeId = memberTypeId;
        this.memberTypeName = memberTypeName;
        this.vipLevel = vipLevel;
        this.buyTime = buyTime;
        this.endTime = endTime;
        this.aging = aging;
        this.birthday = birthday;
        this.points = points;
        this.lastLogin = lastLogin;
        this.lastLoginip = lastLoginip;
        this.registerTime = registerTime;
        this.registerIp = registerIp;
        this.uuidToken = uuidToken;
        this.totalMoney = totalMoney;
        this.isLock = isLock;
        this.isDel = isDel;
        this.gmtCreated = gmtCreated;
        this.gmtModified = gmtModified;
        this.picAddress = picAddress;
        this.favoritesIds = favoritesIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cps_member
     *
     * @mbggenerated
     */
    public CpsMember() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.id
     *
     * @return the value of cps_member.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.id
     *
     * @param id the value for cps_member.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.username
     *
     * @return the value of cps_member.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.username
     *
     * @param username the value for cps_member.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.nickname
     *
     * @return the value of cps_member.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.nickname
     *
     * @param nickname the value for cps_member.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.password
     *
     * @return the value of cps_member.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.password
     *
     * @param password the value for cps_member.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.Md5_password
     *
     * @return the value of cps_member.Md5_password
     *
     * @mbggenerated
     */
    public String getMd5Password() {
        return md5Password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.Md5_password
     *
     * @param md5Password the value for cps_member.Md5_password
     *
     * @mbggenerated
     */
    public void setMd5Password(String md5Password) {
        this.md5Password = md5Password == null ? null : md5Password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.gender
     *
     * @return the value of cps_member.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.gender
     *
     * @param gender the value for cps_member.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.mobile
     *
     * @return the value of cps_member.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.mobile
     *
     * @param mobile the value for cps_member.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.qq
     *
     * @return the value of cps_member.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.qq
     *
     * @param qq the value for cps_member.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.weixin
     *
     * @return the value of cps_member.weixin
     *
     * @mbggenerated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.weixin
     *
     * @param weixin the value for cps_member.weixin
     *
     * @mbggenerated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.email
     *
     * @return the value of cps_member.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.email
     *
     * @param email the value for cps_member.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.member_type_id
     *
     * @return the value of cps_member.member_type_id
     *
     * @mbggenerated
     */
    public Integer getMemberTypeId() {
        return memberTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.member_type_id
     *
     * @param memberTypeId the value for cps_member.member_type_id
     *
     * @mbggenerated
     */
    public void setMemberTypeId(Integer memberTypeId) {
        this.memberTypeId = memberTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.member_type_name
     *
     * @return the value of cps_member.member_type_name
     *
     * @mbggenerated
     */
    public String getMemberTypeName() {
        return memberTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.member_type_name
     *
     * @param memberTypeName the value for cps_member.member_type_name
     *
     * @mbggenerated
     */
    public void setMemberTypeName(String memberTypeName) {
        this.memberTypeName = memberTypeName == null ? null : memberTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.vip_level
     *
     * @return the value of cps_member.vip_level
     *
     * @mbggenerated
     */
    public Integer getVipLevel() {
        return vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.vip_level
     *
     * @param vipLevel the value for cps_member.vip_level
     *
     * @mbggenerated
     */
    public void setVipLevel(Integer vipLevel) {
        this.vipLevel = vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.buy_time
     *
     * @return the value of cps_member.buy_time
     *
     * @mbggenerated
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.buy_time
     *
     * @param buyTime the value for cps_member.buy_time
     *
     * @mbggenerated
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.end_time
     *
     * @return the value of cps_member.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.end_time
     *
     * @param endTime the value for cps_member.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.aging
     *
     * @return the value of cps_member.aging
     *
     * @mbggenerated
     */
    public Integer getAging() {
        return aging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.aging
     *
     * @param aging the value for cps_member.aging
     *
     * @mbggenerated
     */
    public void setAging(Integer aging) {
        this.aging = aging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.birthday
     *
     * @return the value of cps_member.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.birthday
     *
     * @param birthday the value for cps_member.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.points
     *
     * @return the value of cps_member.points
     *
     * @mbggenerated
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.points
     *
     * @param points the value for cps_member.points
     *
     * @mbggenerated
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.last_login
     *
     * @return the value of cps_member.last_login
     *
     * @mbggenerated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.last_login
     *
     * @param lastLogin the value for cps_member.last_login
     *
     * @mbggenerated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.last_loginIp
     *
     * @return the value of cps_member.last_loginIp
     *
     * @mbggenerated
     */
    public String getLastLoginip() {
        return lastLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.last_loginIp
     *
     * @param lastLoginip the value for cps_member.last_loginIp
     *
     * @mbggenerated
     */
    public void setLastLoginip(String lastLoginip) {
        this.lastLoginip = lastLoginip == null ? null : lastLoginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.register_time
     *
     * @return the value of cps_member.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.register_time
     *
     * @param registerTime the value for cps_member.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.register_ip
     *
     * @return the value of cps_member.register_ip
     *
     * @mbggenerated
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.register_ip
     *
     * @param registerIp the value for cps_member.register_ip
     *
     * @mbggenerated
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.UUID_token
     *
     * @return the value of cps_member.UUID_token
     *
     * @mbggenerated
     */
    public String getUuidToken() {
        return uuidToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.UUID_token
     *
     * @param uuidToken the value for cps_member.UUID_token
     *
     * @mbggenerated
     */
    public void setUuidToken(String uuidToken) {
        this.uuidToken = uuidToken == null ? null : uuidToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.total_money
     *
     * @return the value of cps_member.total_money
     *
     * @mbggenerated
     */
    public Integer getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.total_money
     *
     * @param totalMoney the value for cps_member.total_money
     *
     * @mbggenerated
     */
    public void setTotalMoney(Integer totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.is_lock
     *
     * @return the value of cps_member.is_lock
     *
     * @mbggenerated
     */
    public Integer getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.is_lock
     *
     * @param isLock the value for cps_member.is_lock
     *
     * @mbggenerated
     */
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.is_del
     *
     * @return the value of cps_member.is_del
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.is_del
     *
     * @param isDel the value for cps_member.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.gmt_created
     *
     * @return the value of cps_member.gmt_created
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.gmt_created
     *
     * @param gmtCreated the value for cps_member.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.gmt_modified
     *
     * @return the value of cps_member.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.gmt_modified
     *
     * @param gmtModified the value for cps_member.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.pic_address
     *
     * @return the value of cps_member.pic_address
     *
     * @mbggenerated
     */
    public String getPicAddress() {
        return picAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.pic_address
     *
     * @param picAddress the value for cps_member.pic_address
     *
     * @mbggenerated
     */
    public void setPicAddress(String picAddress) {
        this.picAddress = picAddress == null ? null : picAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cps_member.favorites_ids
     *
     * @return the value of cps_member.favorites_ids
     *
     * @mbggenerated
     */
    public String getFavoritesIds() {
        return favoritesIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cps_member.favorites_ids
     *
     * @param favoritesIds the value for cps_member.favorites_ids
     *
     * @mbggenerated
     */
    public void setFavoritesIds(String favoritesIds) {
        this.favoritesIds = favoritesIds == null ? null : favoritesIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cps_member
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", nickname=").append(nickname);
        sb.append(", password=").append(password);
        sb.append(", md5Password=").append(md5Password);
        sb.append(", gender=").append(gender);
        sb.append(", mobile=").append(mobile);
        sb.append(", qq=").append(qq);
        sb.append(", weixin=").append(weixin);
        sb.append(", email=").append(email);
        sb.append(", memberTypeId=").append(memberTypeId);
        sb.append(", memberTypeName=").append(memberTypeName);
        sb.append(", vipLevel=").append(vipLevel);
        sb.append(", buyTime=").append(buyTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", aging=").append(aging);
        sb.append(", birthday=").append(birthday);
        sb.append(", points=").append(points);
        sb.append(", lastLogin=").append(lastLogin);
        sb.append(", lastLoginip=").append(lastLoginip);
        sb.append(", registerTime=").append(registerTime);
        sb.append(", registerIp=").append(registerIp);
        sb.append(", uuidToken=").append(uuidToken);
        sb.append(", totalMoney=").append(totalMoney);
        sb.append(", isLock=").append(isLock);
        sb.append(", isDel=").append(isDel);
        sb.append(", gmtCreated=").append(gmtCreated);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", picAddress=").append(picAddress);
        sb.append(", favoritesIds=").append(favoritesIds);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}