package com.example.demo.dao;

import com.example.demo.model.CpsMember;
import java.util.List;

public interface CpsMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cps_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cps_member
     *
     * @mbggenerated
     */
    int insert(CpsMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cps_member
     *
     * @mbggenerated
     */
    CpsMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cps_member
     *
     * @mbggenerated
     */
    List<CpsMember> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cps_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CpsMember record);
}